version: '3.8'

services:
  postgres_container:
    image: postgres:16.8-alpine3.20
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: issue_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d issue_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-image
    container_name: app_container
    depends_on:
      postgres_container:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://admin:secret@postgres_container:5432/issue_tracker
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm start"]

volumes:
  postgres_data:
