import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Navbar'
import QueryclientProvider from '@/providers/QueryClientProvider'
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
const inter = Inter({ subsets: ['latin'] })
import {QueryClientProvider,QueryClient} from '@tanstack/react-query'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const queryClient = new QueryClient()

export default function RootLayout({
  children, 
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <QueryclientProvider >
        <Theme>
        <Navbar/>
      
       <main className="p-5">
              {children}
       </main>
        </Theme>
      </QueryclientProvider>
    
      </body>
    </html>
  )
}
