import './globals.css';
import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import Navbar from './Navbar';

import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
// const inter = Inter({ subsets: ['latin'] });
import { QueryClientProvider, QueryClient } from '@tanstack/react-query';
import Provider from '@/providers/provider';
import 'react-toastify/dist/ReactToastify.css';
// 
import { ToastContainer } from 'react-toastify';
import SocketSessionHandler from '@/lib/SocketSessionHandler';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        <Provider>
          <Theme>
            <Navbar />
            <ReactQueryDevtools initialIsOpen={false} />
            <ToastContainer />
            <SocketSessionHandler />
            <main className="p-5">{children}</main>
          </Theme>
        </Provider>
      </body>
    </html>
  );
}
